variable "resource_group_name" {}
variable "location" {}
variable "virtual_network_name" {}
variable "vnet_address_space" {}
variable "subnet1_name" {}
variable "subnet2_name" {}
variable "subnet3_name" {}
variable "subnet1_address_prefix" {}
variable "subnet2_address_prefix" {}
variable "subnet3_address_prefix" {}